project_name: clusterprofile-credentials-plugins

dist: dist

release:
  prerelease: auto
  draft: false

builds:
  - id: eks-aws-auth-plugin
    main: ./cmd/eks-aws-auth-plugin
    binary: eks-aws-auth-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: kubeconfig-secretreader-plugin
    main: ./cmd/kubeconfig-secretreader-plugin
    binary: kubeconfig-secretreader-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: eks-aws-auth-plugin-archive
    builds:
      - eks-aws-auth-plugin
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - cmd/eks-aws-auth-plugin/README.md

  - id: kubeconfig-secretreader-plugin-archive
    builds:
      - kubeconfig-secretreader-plugin
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs?:'
      - '^test:'
      - '^ci:'
      - '^chore:'
